module.exports = {
  Glitch: require('./glitch'),
  Captions: require('./captions'),
  Distortion: require('./distortion'),
  FaceZoom: require('./facezoom'),
  Station: require('./station'),
  Melt: require('./melt'),
  Shuffle: require('./shuffle'),
  Stutter: require('./stutter'),
  Annotate: require('./annotate'),
  Tint: require('./tint'),
  Invert: require('./invert'),
  Gray: require('./gray'),
  Experiment: require('./experiment'),
  Reverse: require('./reverse'),
  Implode: require('./implode'),
  Rotate: require('./rotate'),
  Swirl: require('./swirl'),
  Flip: require('./flip'),
  Flop: require('./flop'),
  FacePinch: require('./facepinch')
};
